### ISSUE TITLE
Make a .tex of Regular Expressions.docx

### ISSUE THREAD

**Issue by Jonan15** [imada-students/course-help#11]
I am not one for docx files.

[link to file](https://github.com/imada-students/course-help/blob/master/DM552/Regular%20Expressions.docx)

**Comment by Median555** [comment]
2 sec, will fix.

**Comment by Median555** [comment]
This is fixed in pull request #16

**Comment by Jonan15** [comment]
Thx for the help.

Fixed in https://github.com/imada-students/course-help/commit/bc77aeb7386698658fb99724240877426e6b51a0
