### ISSUE TITLE
Use upper case for course codes

### ISSUE THREAD

**Issue by JacobAae** [imada-students/course-help#25]
All course codes should be upper case

**Comment by Jonan15** [comment]
I disagree, it's annoying when browsing files using the terminal; it is case-sensitive.

**Comment by Telekinesist** [comment]
If you type with lowercase, then pressing tab, it changes it to upper case

**Comment by Jonan15** [comment]
Not in the standard terminal on Ubuntu.

**Comment by SimonErfurth** [comment]
then you should use a real terminal.
